language: python
python:
        - "2.7"
install: 
        - python setup.py install
        - pip install coveralls
        - pip install stevedorej 
script: nosetests  --with-coverage --cover-package=pyrnassus
after_success:
        coveralls
