language: python
python:
        - "2.7"
sudo: required

install: 
        - sudo apt-get install liblo-dev
        - python setup.py install
        - pip install coveralls
script: nosetests  --with-coverage --cover-package=pyrnassus
after_success:
        coveralls
